### ISSUE TITLE
Keystore was tampered with, or password was incorrect

### ISSUE THREAD

**Issue by vasu018** [esnet/oscars#119]
Hi,

When I run the oscars code base using the ./bin/start.sh the core module is failing with following errors. I have attached the out error messages for your reference. The password authentication is failing with following error messages. I have purged the DB and postgresql and reinstalled it cleanly, still iam facing the same issue. 

Could you please kindly let me know if there is way i can fix this authentication issue. Also, If there is some documentation could you please also kindly refer me to that it will be helpful.

java -jar target/core-1.0.0-beta.jar
2017-07-13 19:34:23.303  INFO 13753 --- [           main] net.es.oscars.CoreApp                    : Starting CoreApp on snake with PID 13753 (/home/vasudevan/oscars-newtech-esnet/core/target/core-1.0.0-beta.jar started by root in /home/vasudevan/oscars-newtech-esnet/core)
2017-07-13 19:34:23.309  INFO 13753 --- [           main] net.es.oscars.CoreApp                    : No active profile set, falling back to default profiles: default
2017-07-13 19:34:23.385  INFO 13753 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@443b7951: startup date [Thu Jul 13 19:34:23 PDT 2017]; root of context hierarchy
2017-07-13 19:34:26.515  INFO 13753 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$e33d1c36] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-07-13 19:34:26.909  INFO 13753 --- [           main] org.xnio                                 : XNIO version 3.3.6.Final
2017-07-13 19:34:26.942  INFO 13753 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.6.Final
2017-07-13 19:34:27.046  WARN 13753 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2017-07-13 19:34:27.046  WARN 13753 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2017-07-13 19:34:27.080  INFO 13753 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2017-07-13 19:34:27.080  INFO 13753 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3699 ms
2017-07-13 19:34:27.309  INFO 13753 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-07-13 19:34:27.310  INFO 13753 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-07-13 19:34:27.310  INFO 13753 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-07-13 19:34:27.310  INFO 13753 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-07-13 19:34:27.311  INFO 13753 --- [           main] .s.DelegatingFilterProxyRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
2017-07-13 19:34:27.311  INFO 13753 --- [           main] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-07-13 19:34:27.507  WARN 13753 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.IllegalStateException: java.io.IOException: Keystore was tampered with, or password was incorrect
2017-07-13 19:34:27.524  INFO 13753 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-07-13 19:34:27.534 ERROR 13753 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.IllegalStateException: java.io.IOException: Keystore was tampered with, or password was incorrect
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537) ~[spring-context-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at net.es.oscars.CoreApp.main(CoreApp.java:19) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [core-1.0.0-beta.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [core-1.0.0-beta.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [core-1.0.0-beta.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [core-1.0.0-beta.jar:na]
Caused by: java.lang.IllegalStateException: java.io.IOException: Keystore was tampered with, or password was incorrect
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getKeyManagers(UndertowEmbeddedServletContainerFactory.java:324) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.configureSsl(UndertowEmbeddedServletContainerFactory.java:270) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.createBuilder(UndertowEmbeddedServletContainerFactory.java:256) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getEmbeddedServletContainer(UndertowEmbeddedServletContainerFactory.java:237) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:164) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	... 16 common frames omitted
Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:780) ~[na:1.8.0_131]
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56) ~[na:1.8.0_131]
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224) ~[na:1.8.0_131]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70) ~[na:1.8.0_131]
	at java.security.KeyStore.load(KeyStore.java:1445) ~[na:1.8.0_131]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.loadKeyStore(UndertowEmbeddedServletContainerFactory.java:378) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getKeyStore(UndertowEmbeddedServletContainerFactory.java:344) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainerFactory.getKeyManagers(UndertowEmbeddedServletContainerFactory.java:310) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	... 21 common frames omitted
Caused by: java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778) ~[na:1.8.0_131]
	... 28 common frames omitted

**Comment by haniotak** [comment]
Hi Vasudevan,

this has to do with the Java keystore configuration in core/config/application.properties . The following config keys need to match your actual keystore location and passwords. The oscars.jks provided by the project is a placeholder; if you've replaced it with your own you will need to make appropriate changes to the config. 

server.ssl.key-store=config/oscars.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=changeit
server.ssl.key-alias=oscars
server.ssl.key-password=changeit

If you haven't touched that file.. well,  cloning the project and building from scratch does not reproduce your issue. 

Please understand this project is a bit unstable and under heavy development right now. I will try to keep the main codebase working but a lot of it will be outright replaced fairly soon.

**Comment by vasu018** [comment]
Hi,

Thanks a lot for very prompt response. Yes, after reverting the application.properties to the original file, the problem is gone. I was getting one more authentication issue (org.postgresql.util.PSQLException: FATAL: password authentication failed for user "oscars").
I added postgres DB entries for "oscars" to fix this authentication issue. 

Now all the authentication issues are gone. But, again the core is failing with different issue. Can you please check the below logs and let me know if i am missing any thing else as I was not able to get any details from the log messages?

root@snake:/home/vasudevan/oscars-newtech-esnet/core# java -jar target/core-1.0.0-beta.jar 
2017-07-14 09:51:16.537  INFO 21350 --- [           main] net.es.oscars.CoreApp                    : Starting CoreApp on snake with PID 21350 (/home/vasudevan/oscars-newtech-esnet/core/target/core-1.0.0-beta.jar started by root in /home/vasudevan/oscars-newtech-esnet/core)
2017-07-14 09:51:16.543  INFO 21350 --- [           main] net.es.oscars.CoreApp                    : No active profile set, falling back to default profiles: default
2017-07-14 09:51:16.619  INFO 21350 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@443b7951: startup date [Fri Jul 14 09:51:16 PDT 2017]; root of context hierarchy
2017-07-14 09:51:19.690  INFO 21350 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$ace23b85] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-07-14 09:51:20.065  INFO 21350 --- [           main] org.xnio                                 : XNIO version 3.3.6.Final
2017-07-14 09:51:20.090  INFO 21350 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.3.6.Final
2017-07-14 09:51:20.197  WARN 21350 --- [           main] io.undertow.websockets.jsr               : UT026009: XNIO worker was not set on WebSocketDeploymentInfo, the default worker will be used
2017-07-14 09:51:20.197  WARN 21350 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
2017-07-14 09:51:20.233  INFO 21350 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
2017-07-14 09:51:20.233  INFO 21350 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3618 ms
2017-07-14 09:51:20.478  INFO 21350 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-07-14 09:51:20.479  INFO 21350 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-07-14 09:51:20.479  INFO 21350 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-07-14 09:51:20.480  INFO 21350 --- [           main] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-07-14 09:51:20.481  INFO 21350 --- [           main] .s.DelegatingFilterProxyRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
2017-07-14 09:51:20.481  INFO 21350 --- [           main] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-07-14 09:51:21.689  INFO 21350 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2017-07-14 09:51:21.713  INFO 21350 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2017-07-14 09:51:21.826  INFO 21350 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.0.12.Final}
2017-07-14 09:51:21.828  INFO 21350 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2017-07-14 09:51:21.830  INFO 21350 --- [           main] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist
2017-07-14 09:51:21.892  INFO 21350 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2017-07-14 09:51:22.357  INFO 21350 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
2017-07-14 09:51:22.549  INFO 21350 --- [           main] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2017-07-14 09:51:22.551  INFO 21350 --- [           main] org.hibernate.type.BasicTypeRegistry     : HHH000270: Type registration [java.util.UUID] overrides previous : org.hibernate.type.UUIDBinaryType@3301500b
2017-07-14 09:51:23.822  INFO 21350 --- [           main] rmationExtractorJdbcDatabaseMetaDataImpl : HHH000262: Table not found: archived_bandwidthe
2017-07-14 09:51:23.824  INFO 21350 --- [           main] rmationExtractorJdbcDatabaseMetaDataImpl : HHH000262: Table not found: archived_bandwidthe
2017-07-14 09:51:23.825  WARN 21350 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
2017-07-14 09:51:23.841  INFO 21350 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-07-14 09:51:23.851 ERROR 21350 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078) ~[spring-context-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857) ~[spring-context-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar!/:1.5.4.RELEASE]
	at net.es.oscars.CoreApp.main(CoreApp.java:19) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [core-1.0.0-beta.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [core-1.0.0-beta.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [core-1.0.0-beta.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [core-1.0.0-beta.jar:na]
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:954) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:882) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) ~[spring-orm-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:353) ~[spring-orm-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:370) ~[spring-orm-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:359) ~[spring-orm-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	... 24 common frames omitted
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing table [archived_bandwidthe]
	at org.hibernate.tool.schema.internal.SchemaValidatorImpl.validateTable(SchemaValidatorImpl.java:67) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.tool.schema.internal.SchemaValidatorImpl.doValidation(SchemaValidatorImpl.java:50) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:91) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:475) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:444) ~[hibernate-core-5.0.12.Final.jar!/:5.0.12.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:879) ~[hibernate-entitymanager-5.0.12.Final.jar!/:5.0.12.Final]
	... 30 common frames omitted

**Comment by haniotak** [comment]
Did you run the bin/install_db.sh script? It will drop and re-create the OSCARS database, setting up the right tables. I have updated the README to reflect that requirement.

**Comment by vasu018** [comment]
Thanks a lot. It worked. I can see the applications core and pss are running on port numbers 8001 and 8002. I have also cloned new repo and checked the README. It is fine. 

root@snake:/home/vasudevan/oscars-newtech-esnet# netstat -nl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN     
tcp6       0      0 :::8001                 :::*                    LISTEN     
tcp6       0      0 :::8002                 :::*                    LISTEN     

Also, if there is any master document that can provide the clean steps and details about the end-to-end process it will be really helpful (There are still some more missing steps in running the toosl such as - setting environment variables, installing necessary tools such as postgres, sphinx and so on). I believe this document will make tool very much user friendly. We can add few sample configurations or template file for making this tool user friendly and ready to use. If there is some such existing document I can also refer to that. Now, that i wanted to use the tool and test the reservation procedure, but i am not sure how to test it now.
I will also contribute to that documentation.  

Thanks & Regards

**Comment by haniotak** [comment]
Thank you, any work towards the project is appreciated. Please do not hesitate to submit pull requests, although I recommend holding off about one more week as I am working on some major restructuring that will hopefully make things quite a bit nicer.


I will close this particular issue as it is resolved.

**Comment by vasu018** [comment]
Thanks a lot for resolving this.
