### ISSUE TITLE
HTTP status 500 for a request with invalid endpoints

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars#38]
It looks like something in the core crashes or at least throws an exception if we try to add a connection via the REST API with an invalid endpoint (or with invalid endpoints):

```
hattori:oscars-newtech% core/src/test/python/make-circuit.py --id test2 --bitrate 1 --aport foo-mr2:xe-0/1/0 --zport bar-mr2:xe-1/0/0
Traceback (most recent call last):
  File "core/src/test/python/make-circuit.py", line 111, in <module>
    r.raise_for_status()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://localhost:8000//resv/connection/add
```

There's a fairly long stack trace on the server side corresponding to this action, the top of which is:

```
2017-03-17 14:05:37.910 ERROR 2491 --- [ XNIO-2 task-11] io.undertow.request                      : UT005023: Exception handling request to //resv/connection/add

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is net.es.oscars.pce.PCEException: device not found in topology
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982) ~[spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) ~[spring-webmvc-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
```

This doesn't lend itself well to presenting some sort of helpful message in the Web UI, unless the Web UI back end can somehow figure out what happened pass some appropriate text to the front end.

**Comment by haniotak** [comment]
Added new code to check for invalid URNs and return an informative message. i.e. (with make-circuit -v option):

status 404: {"error_message":"One or more requested URNs not found: foo-mr2,foo-mr2:xe-0/1/0","error":true}
